[package]
name = "RabinKarp"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["fileapi", "handleapi", "memoryapi", "winnt", "minwinbase"] }
indicatif = "0.16"

